export const GET_ALL_POST = "GET_ALL_POST"
export const GET_CANDIDATES = "GET_CANDIDATES"
export const GET_CHATS = "GET_CHATS"
export const GET_MY_PRIVATE_CHAT = "GET_MY_PRIVATE_CHAT"
export const ADD_MESSAGE = 'ADD_MESSAGE';